(source gnu)
(source melpa)
(package-file "lean-mode.el")
(development
 (depends-on "cl-lib")
 (depends-on "company")
 (depends-on "dash" 2.8.0)
 (depends-on "dash-functional" "1.1.0")
 (depends-on "ert-runner")
 (depends-on "ecukes")
 (depends-on "f")
 (depends-on "flycheck")
 (depends-on "flymake")
 (depends-on "fill-column-indicator")
 (depends-on "s"))
