image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - name: Build
    init: cmake --preset dev
    command: make -C build/release -j$(nproc || sysctl -n hw.logicalcpu)
