image:
    file: .gitpod.Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - name: Release build
    init: cmake --preset release
    command: make -C build/release -j$(nproc || sysctl -n hw.logicalcpu)
