import Std.Tactic.BVDecide
example {x : BitVec 8} (h : x = 0#8) : x.popCount = 0 := by bv_decide
example {x : BitVec 8} (h : x = 1#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 2#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 3#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 4#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 5#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 6#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 7#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 8#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 9#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 10#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 11#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 12#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 13#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 14#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 15#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 16#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 17#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 18#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 19#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 20#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 21#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 22#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 23#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 24#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 25#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 26#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 27#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 28#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 29#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 30#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 31#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 32#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 33#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 34#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 35#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 36#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 37#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 38#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 39#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 40#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 41#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 42#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 43#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 44#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 45#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 46#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 47#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 48#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 49#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 50#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 51#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 52#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 53#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 54#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 55#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 56#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 57#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 58#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 59#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 60#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 61#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 62#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 63#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 64#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 65#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 66#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 67#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 68#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 69#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 70#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 71#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 72#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 73#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 74#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 75#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 76#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 77#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 78#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 79#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 80#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 81#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 82#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 83#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 84#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 85#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 86#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 87#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 88#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 89#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 90#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 91#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 92#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 93#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 94#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 95#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 96#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 97#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 98#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 99#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 100#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 101#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 102#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 103#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 104#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 105#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 106#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 107#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 108#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 109#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 110#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 111#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 112#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 113#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 114#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 115#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 116#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 117#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 118#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 119#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 120#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 121#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 122#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 123#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 124#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 125#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 126#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 127#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 128#8) : x.popCount = 1 := by bv_decide
example {x : BitVec 8} (h : x = 129#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 130#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 131#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 132#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 133#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 134#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 135#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 136#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 137#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 138#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 139#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 140#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 141#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 142#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 143#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 144#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 145#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 146#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 147#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 148#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 149#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 150#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 151#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 152#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 153#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 154#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 155#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 156#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 157#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 158#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 159#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 160#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 161#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 162#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 163#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 164#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 165#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 166#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 167#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 168#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 169#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 170#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 171#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 172#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 173#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 174#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 175#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 176#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 177#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 178#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 179#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 180#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 181#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 182#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 183#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 184#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 185#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 186#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 187#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 188#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 189#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 190#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 191#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 192#8) : x.popCount = 2 := by bv_decide
example {x : BitVec 8} (h : x = 193#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 194#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 195#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 196#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 197#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 198#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 199#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 200#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 201#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 202#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 203#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 204#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 205#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 206#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 207#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 208#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 209#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 210#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 211#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 212#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 213#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 214#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 215#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 216#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 217#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 218#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 219#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 220#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 221#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 222#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 223#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 224#8) : x.popCount = 3 := by bv_decide
example {x : BitVec 8} (h : x = 225#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 226#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 227#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 228#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 229#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 230#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 231#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 232#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 233#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 234#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 235#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 236#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 237#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 238#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 239#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 240#8) : x.popCount = 4 := by bv_decide
example {x : BitVec 8} (h : x = 241#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 242#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 243#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 244#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 245#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 246#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 247#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 248#8) : x.popCount = 5 := by bv_decide
example {x : BitVec 8} (h : x = 249#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 250#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 251#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 252#8) : x.popCount = 6 := by bv_decide
example {x : BitVec 8} (h : x = 253#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 254#8) : x.popCount = 7 := by bv_decide
example {x : BitVec 8} (h : x = 255#8) : x.popCount = 8 := by bv_decide
