import Std.Tactic.BVDecide
example {x : BitVec 7} (h : x = 0#7) : x.popCount = 0 := by bv_decide
example {x : BitVec 7} (h : x = 1#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 2#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 3#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 4#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 5#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 6#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 7#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 8#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 9#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 10#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 11#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 12#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 13#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 14#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 15#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 16#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 17#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 18#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 19#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 20#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 21#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 22#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 23#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 24#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 25#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 26#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 27#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 28#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 29#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 30#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 31#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 32#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 33#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 34#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 35#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 36#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 37#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 38#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 39#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 40#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 41#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 42#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 43#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 44#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 45#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 46#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 47#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 48#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 49#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 50#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 51#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 52#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 53#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 54#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 55#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 56#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 57#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 58#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 59#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 60#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 61#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 62#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 63#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 64#7) : x.popCount = 1 := by bv_decide
example {x : BitVec 7} (h : x = 65#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 66#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 67#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 68#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 69#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 70#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 71#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 72#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 73#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 74#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 75#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 76#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 77#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 78#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 79#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 80#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 81#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 82#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 83#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 84#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 85#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 86#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 87#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 88#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 89#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 90#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 91#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 92#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 93#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 94#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 95#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 96#7) : x.popCount = 2 := by bv_decide
example {x : BitVec 7} (h : x = 97#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 98#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 99#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 100#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 101#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 102#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 103#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 104#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 105#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 106#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 107#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 108#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 109#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 110#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 111#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 112#7) : x.popCount = 3 := by bv_decide
example {x : BitVec 7} (h : x = 113#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 114#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 115#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 116#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 117#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 118#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 119#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 120#7) : x.popCount = 4 := by bv_decide
example {x : BitVec 7} (h : x = 121#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 122#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 123#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 124#7) : x.popCount = 5 := by bv_decide
example {x : BitVec 7} (h : x = 125#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 126#7) : x.popCount = 6 := by bv_decide
example {x : BitVec 7} (h : x = 127#7) : x.popCount = 7 := by bv_decide
