import Std.Tactic.BVDecide
example {x : BitVec 9} (h : x = 0#9) : x.popCount = 0 := by bv_decide
example {x : BitVec 9} (h : x = 1#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 2#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 3#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 4#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 5#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 6#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 7#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 8#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 9#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 10#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 11#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 12#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 13#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 14#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 15#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 16#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 17#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 18#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 19#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 20#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 21#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 22#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 23#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 24#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 25#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 26#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 27#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 28#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 29#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 30#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 31#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 32#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 33#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 34#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 35#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 36#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 37#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 38#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 39#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 40#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 41#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 42#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 43#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 44#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 45#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 46#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 47#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 48#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 49#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 50#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 51#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 52#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 53#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 54#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 55#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 56#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 57#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 58#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 59#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 60#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 61#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 62#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 63#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 64#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 65#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 66#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 67#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 68#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 69#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 70#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 71#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 72#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 73#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 74#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 75#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 76#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 77#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 78#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 79#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 80#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 81#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 82#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 83#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 84#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 85#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 86#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 87#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 88#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 89#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 90#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 91#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 92#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 93#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 94#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 95#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 96#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 97#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 98#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 99#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 100#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 101#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 102#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 103#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 104#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 105#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 106#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 107#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 108#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 109#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 110#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 111#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 112#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 113#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 114#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 115#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 116#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 117#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 118#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 119#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 120#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 121#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 122#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 123#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 124#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 125#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 126#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 127#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 128#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 129#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 130#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 131#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 132#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 133#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 134#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 135#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 136#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 137#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 138#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 139#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 140#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 141#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 142#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 143#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 144#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 145#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 146#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 147#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 148#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 149#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 150#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 151#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 152#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 153#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 154#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 155#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 156#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 157#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 158#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 159#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 160#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 161#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 162#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 163#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 164#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 165#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 166#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 167#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 168#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 169#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 170#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 171#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 172#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 173#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 174#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 175#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 176#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 177#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 178#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 179#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 180#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 181#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 182#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 183#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 184#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 185#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 186#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 187#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 188#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 189#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 190#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 191#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 192#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 193#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 194#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 195#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 196#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 197#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 198#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 199#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 200#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 201#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 202#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 203#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 204#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 205#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 206#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 207#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 208#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 209#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 210#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 211#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 212#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 213#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 214#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 215#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 216#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 217#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 218#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 219#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 220#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 221#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 222#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 223#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 224#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 225#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 226#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 227#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 228#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 229#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 230#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 231#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 232#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 233#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 234#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 235#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 236#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 237#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 238#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 239#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 240#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 241#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 242#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 243#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 244#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 245#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 246#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 247#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 248#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 249#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 250#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 251#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 252#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 253#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 254#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 255#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 256#9) : x.popCount = 1 := by bv_decide
example {x : BitVec 9} (h : x = 257#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 258#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 259#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 260#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 261#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 262#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 263#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 264#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 265#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 266#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 267#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 268#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 269#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 270#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 271#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 272#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 273#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 274#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 275#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 276#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 277#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 278#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 279#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 280#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 281#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 282#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 283#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 284#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 285#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 286#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 287#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 288#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 289#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 290#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 291#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 292#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 293#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 294#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 295#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 296#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 297#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 298#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 299#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 300#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 301#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 302#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 303#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 304#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 305#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 306#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 307#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 308#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 309#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 310#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 311#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 312#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 313#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 314#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 315#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 316#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 317#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 318#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 319#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 320#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 321#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 322#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 323#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 324#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 325#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 326#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 327#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 328#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 329#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 330#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 331#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 332#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 333#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 334#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 335#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 336#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 337#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 338#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 339#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 340#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 341#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 342#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 343#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 344#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 345#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 346#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 347#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 348#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 349#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 350#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 351#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 352#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 353#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 354#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 355#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 356#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 357#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 358#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 359#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 360#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 361#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 362#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 363#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 364#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 365#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 366#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 367#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 368#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 369#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 370#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 371#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 372#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 373#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 374#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 375#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 376#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 377#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 378#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 379#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 380#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 381#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 382#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 383#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 384#9) : x.popCount = 2 := by bv_decide
example {x : BitVec 9} (h : x = 385#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 386#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 387#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 388#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 389#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 390#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 391#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 392#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 393#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 394#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 395#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 396#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 397#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 398#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 399#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 400#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 401#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 402#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 403#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 404#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 405#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 406#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 407#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 408#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 409#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 410#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 411#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 412#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 413#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 414#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 415#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 416#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 417#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 418#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 419#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 420#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 421#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 422#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 423#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 424#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 425#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 426#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 427#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 428#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 429#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 430#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 431#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 432#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 433#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 434#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 435#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 436#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 437#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 438#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 439#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 440#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 441#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 442#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 443#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 444#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 445#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 446#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 447#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 448#9) : x.popCount = 3 := by bv_decide
example {x : BitVec 9} (h : x = 449#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 450#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 451#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 452#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 453#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 454#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 455#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 456#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 457#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 458#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 459#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 460#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 461#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 462#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 463#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 464#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 465#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 466#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 467#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 468#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 469#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 470#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 471#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 472#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 473#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 474#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 475#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 476#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 477#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 478#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 479#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 480#9) : x.popCount = 4 := by bv_decide
example {x : BitVec 9} (h : x = 481#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 482#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 483#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 484#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 485#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 486#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 487#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 488#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 489#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 490#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 491#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 492#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 493#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 494#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 495#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 496#9) : x.popCount = 5 := by bv_decide
example {x : BitVec 9} (h : x = 497#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 498#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 499#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 500#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 501#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 502#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 503#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 504#9) : x.popCount = 6 := by bv_decide
example {x : BitVec 9} (h : x = 505#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 506#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 507#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 508#9) : x.popCount = 7 := by bv_decide
example {x : BitVec 9} (h : x = 509#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 510#9) : x.popCount = 8 := by bv_decide
example {x : BitVec 9} (h : x = 511#9) : x.popCount = 9 := by bv_decide
