// Lean compiler output
// Module: Lean.Meta.Tactic.Try
// Imports: Lean.Meta.Tactic.Try.Collect
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_53_(lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_;
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_200_(lean_object*);
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_102_(lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_;
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_4_(lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_;
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_151_(lean_object*);
lean_object* l_Lean_Name_mkStr3(lean_object*, lean_object*, lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_;
lean_object* l_Lean_registerTraceClass(lean_object*, uint8_t, lean_object*, lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_;
lean_object* l_Lean_Name_num___override(lean_object*, lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_;
lean_object* l_Lean_Name_str___override(lean_object*, lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_;
lean_object* l_Lean_Name_mkStr2(lean_object*, lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_;
lean_object* l_Lean_Name_mkStr1(lean_object*);
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_;
static lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_;
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_249_(lean_object*);
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("try", 3, 3);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l_Lean_Name_mkStr1(x_1);
return x_2;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("_private", 8, 8);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = lean_box(0);
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Lean", 4, 4);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Meta", 4, 4);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Tactic", 6, 6);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Try", 3, 3);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(0u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("initFn", 6, 6);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("_@", 2, 2);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("_hyg", 4, 4);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_str___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(4u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_4_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("collect", 7, 7);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_mkStr2(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(53u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_53_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("funInd", 6, 6);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_;
x_3 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(102u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_102_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("debug", 5, 5);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_mkStr2(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(151u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_151_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_;
x_3 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(200u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_200_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("chain", 5, 5);
return x_1;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_;
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_;
x_3 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_unsigned_to_nat(249u);
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_;
x_3 = l_Lean_Name_num___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_249_(lean_object* x_1) {
_start:
{
lean_object* x_2; uint8_t x_3; lean_object* x_4; lean_object* x_5; 
x_2 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_;
x_3 = 0;
x_4 = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_;
x_5 = l_Lean_registerTraceClass(x_2, x_3, x_4, x_1);
return x_5;
}
}
lean_object* initialize_Lean_Meta_Tactic_Try_Collect(uint8_t builtin, lean_object*);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Lean_Meta_Tactic_Try(uint8_t builtin, lean_object* w) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Lean_Meta_Tactic_Try_Collect(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__3____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__4____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__5____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__6____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__7____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__8____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__9____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__10____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__11____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__12____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__13____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__14____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__15____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__16____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__17____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__18____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__19____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__20____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__21____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__22____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__23____x40_Lean_Meta_Tactic_Try___hyg_4_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__24____x40_Lean_Meta_Tactic_Try___hyg_4_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_4_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_53_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_53_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_53_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_53_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_102_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_102_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_102_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_102_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_151_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_151_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_151_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_151_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_200_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_200_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_200_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__0____x40_Lean_Meta_Tactic_Try___hyg_249_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__1____x40_Lean_Meta_Tactic_Try___hyg_249_);
l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_ = _init_l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_();
lean_mark_persistent(l___private_Lean_Meta_Tactic_Try_0__Lean_initFn___closed__2____x40_Lean_Meta_Tactic_Try___hyg_249_);
if (builtin) {res = l___private_Lean_Meta_Tactic_Try_0__Lean_initFn____x40_Lean_Meta_Tactic_Try___hyg_249_(lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
}return lean_io_result_mk_ok(lean_box(0));
}
#ifdef __cplusplus
}
#endif
