// Lean compiler output
// Module: Lean.Util.SearchPath
// Imports: Lean.ToExpr Lean.Util.Path Lean.Elab.Term
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Expr_const___override(lean_object*, lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12;
static lean_object* l_termCompile__time__search__path_x25___closed__1;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15;
static lean_object* l_termCompile__time__search__path_x25___closed__3;
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_mkAppB(lean_object*, lean_object*, lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9;
LEAN_EXPORT lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1;
uint8_t l_Lean_Syntax_isOfKind(lean_object*, lean_object*);
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg(lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14;
lean_object* l_Lean_Name_mkStr3(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_mkStrLit(lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4;
static lean_object* l_termCompile__time__search__path_x25___closed__4;
lean_object* l_Lean_MessageData_ofFormat(lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5;
LEAN_EXPORT lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* lean_st_ref_get(lean_object*, lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2;
static lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3;
lean_object* l_Lean_Name_str___override(lean_object*, lean_object*);
static lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1;
LEAN_EXPORT lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(lean_object*, lean_object*, lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7;
static lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4;
static lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2;
lean_object* l_Lean_Expr_app___override(lean_object*, lean_object*);
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
extern lean_object* l_Lean_searchPathRef;
lean_object* l_Lean_Name_mkStr2(lean_object*, lean_object*);
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10;
LEAN_EXPORT lean_object* l_termCompile__time__search__path_x25;
lean_object* l_Lean_logWarning___at___private_Lean_Elab_Term_0__Lean_Elab_Term_checkDeprecatedCore___spec__2(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3;
LEAN_EXPORT lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___boxed(lean_object*, lean_object*, lean_object*);
static lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2;
static lean_object* l_termCompile__time__search__path_x25___closed__2;
extern lean_object* l_Lean_Elab_unsupportedSyntaxExceptionId;
static lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6;
static lean_object* l_termCompile__time__search__path_x25___closed__5;
static lean_object* _init_l_termCompile__time__search__path_x25___closed__1() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("termCompile_time_search_path%", 29, 29);
return x_1;
}
}
static lean_object* _init_l_termCompile__time__search__path_x25___closed__2() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_box(0);
x_2 = l_termCompile__time__search__path_x25___closed__1;
x_3 = l_Lean_Name_str___override(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l_termCompile__time__search__path_x25___closed__3() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("compile_time_search_path%", 25, 25);
return x_1;
}
}
static lean_object* _init_l_termCompile__time__search__path_x25___closed__4() {
_start:
{
lean_object* x_1; lean_object* x_2; 
x_1 = l_termCompile__time__search__path_x25___closed__3;
x_2 = lean_alloc_ctor(5, 1, 0);
lean_ctor_set(x_2, 0, x_1);
return x_2;
}
}
static lean_object* _init_l_termCompile__time__search__path_x25___closed__5() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l_termCompile__time__search__path_x25___closed__2;
x_2 = lean_unsigned_to_nat(1024u);
x_3 = l_termCompile__time__search__path_x25___closed__4;
x_4 = lean_alloc_ctor(3, 3, 0);
lean_ctor_set(x_4, 0, x_1);
lean_ctor_set(x_4, 1, x_2);
lean_ctor_set(x_4, 2, x_3);
return x_4;
}
}
static lean_object* _init_l_termCompile__time__search__path_x25() {
_start:
{
lean_object* x_1; 
x_1 = l_termCompile__time__search__path_x25___closed__5;
return x_1;
}
}
static lean_object* _init_l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Elab_unsupportedSyntaxExceptionId;
return x_1;
}
}
static lean_object* _init_l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_box(0);
x_2 = l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1;
x_3 = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(x_3, 0, x_2);
lean_ctor_set(x_3, 1, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg(lean_object* x_1) {
_start:
{
lean_object* x_2; lean_object* x_3; 
x_2 = l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2;
x_3 = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(x_3, 0, x_2);
lean_ctor_set(x_3, 1, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1(lean_object* x_1, lean_object* x_2, lean_object* x_3, lean_object* x_4, lean_object* x_5, lean_object* x_6) {
_start:
{
lean_object* x_7; 
x_7 = lean_alloc_closure((void*)(l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg), 1, 0);
return x_7;
}
}
static lean_object* _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("System", 6, 6);
return x_1;
}
}
static lean_object* _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("FilePath", 8, 8);
return x_1;
}
}
static lean_object* _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("mk", 2, 2);
return x_1;
}
}
static lean_object* _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1;
x_2 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2;
x_3 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3;
x_4 = l_Lean_Name_mkStr3(x_1, x_2, x_3);
return x_4;
}
}
static lean_object* _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_box(0);
x_2 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4;
x_3 = l_Lean_Expr_const___override(x_2, x_1);
return x_3;
}
}
LEAN_EXPORT lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(lean_object* x_1, lean_object* x_2, lean_object* x_3) {
_start:
{
if (lean_obj_tag(x_3) == 0)
{
lean_dec(x_2);
lean_inc(x_1);
return x_1;
}
else
{
lean_object* x_4; lean_object* x_5; lean_object* x_6; lean_object* x_7; lean_object* x_8; lean_object* x_9; lean_object* x_10; 
x_4 = lean_ctor_get(x_3, 0);
lean_inc(x_4);
x_5 = lean_ctor_get(x_3, 1);
lean_inc(x_5);
lean_dec(x_3);
x_6 = l_Lean_mkStrLit(x_4);
x_7 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5;
x_8 = l_Lean_Expr_app___override(x_7, x_6);
lean_inc(x_2);
x_9 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(x_1, x_2, x_5);
x_10 = l_Lean_mkAppB(x_2, x_8, x_9);
return x_10;
}
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("`compile_time_search_path%` is deprecated; use `initSearchPath (← findSysroot)` instead.", 90, 88);
return x_1;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2() {
_start:
{
lean_object* x_1; lean_object* x_2; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1;
x_2 = lean_alloc_ctor(3, 1, 0);
lean_ctor_set(x_2, 0, x_1);
return x_2;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3() {
_start:
{
lean_object* x_1; lean_object* x_2; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2;
x_2 = l_Lean_MessageData_ofFormat(x_1);
return x_2;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_searchPathRef;
return x_1;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1;
x_2 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2;
x_3 = l_Lean_Name_mkStr2(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_box(0);
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5;
x_3 = l_Lean_Expr_const___override(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("List", 4, 4);
return x_1;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("nil", 3, 3);
return x_1;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8;
x_3 = l_Lean_Name_mkStr2(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = lean_box(0);
x_2 = lean_box(0);
x_3 = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(x_3, 0, x_2);
lean_ctor_set(x_3, 1, x_1);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10;
x_3 = l_Lean_Expr_const___override(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6;
x_3 = l_Lean_Expr_app___override(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("cons", 4, 4);
return x_1;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13;
x_3 = l_Lean_Name_mkStr2(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10;
x_3 = l_Lean_Expr_const___override(x_1, x_2);
return x_3;
}
}
static lean_object* _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15;
x_2 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6;
x_3 = l_Lean_Expr_app___override(x_1, x_2);
return x_3;
}
}
LEAN_EXPORT lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1(lean_object* x_1, lean_object* x_2, lean_object* x_3, lean_object* x_4, lean_object* x_5, lean_object* x_6, lean_object* x_7, lean_object* x_8, lean_object* x_9) {
_start:
{
lean_object* x_10; uint8_t x_11; 
x_10 = l_termCompile__time__search__path_x25___closed__2;
x_11 = l_Lean_Syntax_isOfKind(x_1, x_10);
if (x_11 == 0)
{
lean_object* x_12; 
lean_dec(x_7);
x_12 = l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg(x_9);
return x_12;
}
else
{
lean_object* x_13; lean_object* x_14; lean_object* x_15; lean_object* x_16; lean_object* x_17; uint8_t x_18; 
x_13 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3;
x_14 = l_Lean_logWarning___at___private_Lean_Elab_Term_0__Lean_Elab_Term_checkDeprecatedCore___spec__2(x_13, x_3, x_4, x_5, x_6, x_7, x_8, x_9);
x_15 = lean_ctor_get(x_14, 1);
lean_inc(x_15);
lean_dec(x_14);
x_16 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4;
x_17 = lean_st_ref_get(x_16, x_15);
x_18 = !lean_is_exclusive(x_17);
if (x_18 == 0)
{
lean_object* x_19; lean_object* x_20; lean_object* x_21; lean_object* x_22; 
x_19 = lean_ctor_get(x_17, 0);
x_20 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12;
x_21 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16;
x_22 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(x_20, x_21, x_19);
lean_ctor_set(x_17, 0, x_22);
return x_17;
}
else
{
lean_object* x_23; lean_object* x_24; lean_object* x_25; lean_object* x_26; lean_object* x_27; lean_object* x_28; 
x_23 = lean_ctor_get(x_17, 0);
x_24 = lean_ctor_get(x_17, 1);
lean_inc(x_24);
lean_inc(x_23);
lean_dec(x_17);
x_25 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12;
x_26 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16;
x_27 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(x_25, x_26, x_23);
x_28 = lean_alloc_ctor(0, 2, 0);
lean_ctor_set(x_28, 0, x_27);
lean_ctor_set(x_28, 1, x_24);
return x_28;
}
}
}
}
LEAN_EXPORT lean_object* l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___boxed(lean_object* x_1, lean_object* x_2, lean_object* x_3, lean_object* x_4, lean_object* x_5, lean_object* x_6) {
_start:
{
lean_object* x_7; 
x_7 = l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1(x_1, x_2, x_3, x_4, x_5, x_6);
lean_dec(x_6);
lean_dec(x_5);
lean_dec(x_4);
lean_dec(x_3);
lean_dec(x_2);
lean_dec(x_1);
return x_7;
}
}
LEAN_EXPORT lean_object* l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___boxed(lean_object* x_1, lean_object* x_2, lean_object* x_3) {
_start:
{
lean_object* x_4; 
x_4 = l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2(x_1, x_2, x_3);
lean_dec(x_1);
return x_4;
}
}
LEAN_EXPORT lean_object* l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___boxed(lean_object* x_1, lean_object* x_2, lean_object* x_3, lean_object* x_4, lean_object* x_5, lean_object* x_6, lean_object* x_7, lean_object* x_8, lean_object* x_9) {
_start:
{
lean_object* x_10; 
x_10 = l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1(x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9);
lean_dec(x_8);
lean_dec(x_6);
lean_dec(x_5);
lean_dec(x_4);
lean_dec(x_3);
lean_dec(x_2);
return x_10;
}
}
lean_object* initialize_Lean_ToExpr(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Util_Path(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Elab_Term(uint8_t builtin, lean_object*);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Lean_Util_SearchPath(uint8_t builtin, lean_object* w) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Lean_ToExpr(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Util_Path(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Elab_Term(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
l_termCompile__time__search__path_x25___closed__1 = _init_l_termCompile__time__search__path_x25___closed__1();
lean_mark_persistent(l_termCompile__time__search__path_x25___closed__1);
l_termCompile__time__search__path_x25___closed__2 = _init_l_termCompile__time__search__path_x25___closed__2();
lean_mark_persistent(l_termCompile__time__search__path_x25___closed__2);
l_termCompile__time__search__path_x25___closed__3 = _init_l_termCompile__time__search__path_x25___closed__3();
lean_mark_persistent(l_termCompile__time__search__path_x25___closed__3);
l_termCompile__time__search__path_x25___closed__4 = _init_l_termCompile__time__search__path_x25___closed__4();
lean_mark_persistent(l_termCompile__time__search__path_x25___closed__4);
l_termCompile__time__search__path_x25___closed__5 = _init_l_termCompile__time__search__path_x25___closed__5();
lean_mark_persistent(l_termCompile__time__search__path_x25___closed__5);
l_termCompile__time__search__path_x25 = _init_l_termCompile__time__search__path_x25();
lean_mark_persistent(l_termCompile__time__search__path_x25);
l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1 = _init_l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1();
lean_mark_persistent(l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__1);
l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2 = _init_l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2();
lean_mark_persistent(l_Lean_Elab_throwUnsupportedSyntax___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__1___rarg___closed__2);
l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1 = _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1();
lean_mark_persistent(l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__1);
l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2 = _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2();
lean_mark_persistent(l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__2);
l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3 = _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3();
lean_mark_persistent(l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__3);
l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4 = _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4();
lean_mark_persistent(l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__4);
l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5 = _init_l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5();
lean_mark_persistent(l___private_Lean_ToExpr_0__Lean_List_toExprAux___at___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___spec__2___closed__5);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__1);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__2);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__3);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__4);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__5);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__6);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__7);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__8);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__9);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__10);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__11);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__12);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__13);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__14);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__15);
l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16 = _init_l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16();
lean_mark_persistent(l___aux__Lean__Util__SearchPath______elabRules__termCompile__time__search__path_x25__1___closed__16);
return lean_io_result_mk_ok(lean_box(0));
}
#ifdef __cplusplus
}
#endif
