local env = bare_environment()
assert(is_environment(env))
assert(not env:is_universe("U"))
local env2 = env:add_universe("U")
assert(not env:is_universe("U"))
assert(env2:is_universe("U"))
assert(env:eta())
assert(env:prop_proof_irrel())
assert(env:impredicative())
