assert(not empty_environment({eta=false}):eta())
assert(empty_environment({eta=true}):eta())
assert(not empty_environment({prop_proof_irrel=false}):prop_proof_irrel())
assert(empty_environment({prop_proof_irrel=true}):prop_proof_irrel())
assert(empty_environment({impredicative=true}):impredicative())
assert(not empty_environment({impredicative=false}):impredicative())
assert(empty_environment({trust_lvl=10}):trust_lvl() == 10)
assert(empty_environment({trust_lvl=0}):trust_lvl() == 0)
assert(empty_environment():trust_lvl() == 0)
