assert(not empty_environment({eta=false}):eta())
assert(empty_environment({eta=true}):eta())
assert(not empty_environment({proof_irrel=false}):proof_irrel())
assert(not empty_environment({proof_irrel=false}):proof_irrelevance())
assert(empty_environment({proof_irrel=true}):proof_irrelevance())
assert(empty_environment({impredicative=true}):impredicative())
assert(not empty_environment({impredicative=false}):impredicative())
assert(empty_environment({trust_lvl=10}):trust_lvl() == 10)
assert(empty_environment({trust_lvl=0}):trust_lvl() == 0)
assert(empty_environment():trust_lvl() == 0)
