local Or = Const("or")
local A  = Local("A", Type)
local a  = Local("a", A)
local b  = Local("b", A)
local H  = Local("H", Or(a, b))
print(Pi({A, {a, true}, {b, Bool}, {H, binder_info(false, true)}}, Or(b, a)))
print(Pi({A, a, b, H}, Or(b, a)))
print(Fun({A, {a, true}, {b, Bool}, {H, binder_info(false, true)}}, Or(b, a)))
print(Fun({A, a, b, H}, Or(b, a)))
