local env = environment()
local f = Local("f", mk_arrow(Bool, Bool, Bool))
local a = Local("a", Bool)
local b = Local("b", Bool)
local x = Local("x", Bool)
local t = Fun({f, a, b}, f(Fun(x, x)(b), a))
print(env:normalize(t))
assert(env:normalize(t) == Fun({f, a, b}, f(b, a)))
