print(format("hello"):highlight("green"))
print(format("hello"):highlight("orange"))
print(format("hello"):highlight("blue"))
print(format("hello"):highlight("cyan"))
print(format("hello"):highlight("grey"))
print(format("hello"):highlight("red"))
check_error(function() print(format("hello"):highlight("xyz")) end)
print(format())
print(format(mpz(10)))
print(format(mpq(10)/3))
