l = level()
assert(is_bottom(l))
assert(is_level(l))
l = level(l, 1)
assert(is_level(l))
assert(not is_bottom(l))
assert(is_lift(l))
assert(lift_of(l) == level())
assert(lift_offset(l) == 1)
l = level("U")
assert(is_uvar(l))
assert(uvar_name(l) == name("U"))
assert(not is_lift(l))
l = level(level("U"), level("M"), level("m"))
assert(is_max(l))
assert(max_size(l) == 3)
assert(max_level(l, 0) == level("U"))
assert(max_level(l, 1) == level("M"))
print(l)
