local g   = mk_global_univ("g")
local g1  = mk_level_succ(g)
local g2  = mk_level_succ(g1)
local g3  = mk_level_succ(g2)
local g1b = mk_level_succ(mk_global_univ("g"))
assert(mk_level_max(g, g1) == g1)
assert(mk_level_max(g2, g1) == g2)
assert(mk_level_max(g3, g2) == g3)
assert(mk_level_max(g2, g3) == g3)
assert(mk_level_max(g1b, g2) == g2)
assert(mk_level_max(g1b, g) == g1b)
assert(mk_level_max(g, g1b) == g1b)
assert(not (mk_level_max(mk_global_univ("g2"), g1b) == g1b))

assert(mk_level_imax(g2, g3) == g3)
assert(not (mk_level_imax(g3, g) == g3))
assert(mk_level_imax(g3, g1) == g3)
