opts = options()
assert(is_options(opts))
opts = opts:update(name('pp', 'colors'), false)
opts = opts:update(name('pp', 'colors'), true)
print(opts)
assert(is_options(opts))
assert(not is_options(name("foo")))
assert(not is_options("foo"))
assert(not is_options({}))
