print(mk_expr_placeholder())
print(mk_level_placeholder())
assert(is_placeholder(mk_expr_placeholder()))
assert(not is_placeholder(Var(0)))
assert(not is_placeholder(Const("A")))
assert(is_placeholder(mk_level_placeholder()))
assert(not is_placeholder(param_univ("l")))
local f = Const("f")
local a = Const("a")
assert(has_placeholder(f(mk_expr_placeholder())))
assert(not has_placeholder(f(a)))
assert(has_placeholder(f(Const("a", { mk_level_placeholder() }))))
assert(has_placeholder(mk_sort(mk_level_placeholder())))
assert(has_placeholder(mk_sort(max_univ(1, mk_level_placeholder()))))
