if (MIMALLOC_FOUND)
  # Already in cache, be silent
  set(MIMALLOC_FIND_QUIETLY TRUE)
endif (MIMALLOC_FOUND)

find_package(PkgConfig REQUIRED)
pkg_search_module(MIMALLOC REQUIRED mimalloc)
MESSAGE(STATUS "MIMALLOC_LDFLAGS: " ${MIMALLOC_LDFLAGS})
MESSAGE(STATUS "MIMALLOC_INCLUDE_DIRS: " ${MIMALLOC_INCLUDE_DIRS})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Mimalloc DEFAULT_MSG MIMALLOC_FOUND)
mark_as_advanced(MIMALLOC_INCLUDE_DIRS MIMALLOC_LDFLAGS)
