if (LIBUV_FOUND)
  # Already in cache, be silent
  set(LIBUV_FIND_QUIETLY TRUE)
endif (LIBUV_FOUND)

find_package(PkgConfig REQUIRED)
pkg_search_module(LIBUV REQUIRED libuv)
MESSAGE(STATUS "LIBUV_LDFLAGS: " ${LIBUV_LDFLAGS})
MESSAGE(STATUS "LIBUV_INCLUDE_DIRS: " ${LIBUV_INCLUDE_DIRS})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibUV DEFAULT_MSG LIBUV_FOUND)
mark_as_advanced(LIBUV_INCLUDE_DIRS LIBUV_LDFLAGS)
