if (LIBIDN2_INCLUDE_DIR AND LIBIDN2_LIBRARIES)
    set(LIBIDN2_FIND_QUIETLY TRUE)
endif (LIBIDN2_INCLUDE_DIR AND LIBIDN2_LIBRARIES)

find_path(LIBIDN2_INCLUDE_DIR NAMES idn2.h)
find_library(LIBIDN2_LIBRARIES NAMES idn2 REQUIRED)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibIDN2 DEFAULT_MSG LIBIDN2_INCLUDE_DIR LIBIDN2_LIBRARIES)

mark_as_advanced(LIBIDN2_INCLUDE_DIR LIBIDN2_LIBRARIES)