if (LIBIDN2_INCLUDE_DIRS AND LIBIDN2_LDFLAGS)
    set(LIBIDN2_FIND_QUIETLY TRUE)
endif (LIBIDN2_INCLUDE_DIRS AND LIBIDN2_LDFLAGS)

find_path(LIBIDN2_INCLUDE_DIRS NAMES idn2.h)
find_library(LIBIDN2_LDFLAGS NAMES idn2 REQUIRED)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibIDN2 DEFAULT_MSG LIBIDN2_INCLUDE_DIRS LIBIDN2_LDFLAGS)

mark_as_advanced(LIBIDN2_INCLUDE_DIRS LIBIDN2_LDFLAGS)