/*
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
*/

#define lean_io_result_show_error leanrt_cpp_partial_hidden_result_show_error_impl
#define lean_io_mark_end_initialization leanrt_cpp_partial_hidden_mark_end_init_impl
#define lean_io_initializing leanrt_cpp_partial_hidden_initializing_impl
#define lean_decode_io_error leanrt_cpp_partial_hidden_decode_io_error_impl
#define lean_decode_uv_error leanrt_cpp_partial_hidden_decode_uv_error_impl
#define lean_st_mk_ref leanrt_cpp_partial_hidden_lean_st_mk_ref_impl
#define lean_st_ref_get leanrt_cpp_partial_hidden_lean_st_ref_get_impl
#define lean_st_ref_set leanrt_cpp_partial_hidden_lean_st_ref_set_impl
#define lean_st_ref_swap leanrt_cpp_partial_hidden_lean_st_ref_swap_impl

#include <runtime/io.cpp>
