#!/usr/bin/env bash
source ../env_test.sh
source "$TEST_DIR/util.sh"

# IO.Process.exit (used by the file worker) seems to be incompatible with LSAN
# TODO: investigate or work around
export ASAN_OPTIONS=detect_leaks=0

# these tests don't have to succeed
exec_capture "$1" \
  lean -Dlinter.all=false --run run_test.lean "$1"

normalize_mvar_suffixes "$1"
normalize_reference_urls "$1"
check_exit "$1"
check_out "$1"
