Variables p q r : Bool

Theorem T1 : p => p /\ q => r => q /\ r /\ p := _.
    apply (** REPEAT(ORELSE(imp_tactic, conj_tactic, conj_hyp_tactic, assumption_tactic)) **)
    done

(* Display proof term generated by previous tactic *)
Show Environment 1