#!/usr/bin/env bash
source ../../env_test.sh
source "$TEST_DIR/util.sh"

# IO.Process.exit (used by the file worker) seems to be incompatible with LSAN
# TODO: investigate or work around
export ASAN_OPTIONS=detect_leaks=0

lake build

FILE=InverseModuleHierarchy/BasicTest.lean
exec_capture "$FILE" lean -Dlinter.all=false --run run_test.lean -p "$(realpath "$FILE")"
check_exit "$FILE"
check_out "$FILE"
