// Lean compiler output
// Module: Lean.Widget.Basic
// Imports: public import Lean.Elab.InfoTree public import Lean.Message public import Lean.Server.Rpc.Basic public import Lean.Server.InfoUtils public import Lean.Widget.Types
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
static lean_object* l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instTypeNameLocalContext;
lean_object* l_Lean_Name_mkStr3(lean_object*, lean_object*, lean_object*);
static lean_object* l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instTypeNameContextInfo;
LEAN_EXPORT lean_object* l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
lean_object* l_Lean_Name_mkStr2(lean_object*, lean_object*);
static lean_object* l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
static lean_object* l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* l_Lean_Widget_instTypeNameInfoWithCtx;
LEAN_EXPORT lean_object* l_Lean_Widget_instTypeNameTermInfo;
static lean_object* _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Lean", 4, 4);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("Elab", 4, 4);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("InfoWithCtx", 11, 11);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_2 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_3 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instTypeNameInfoWithCtx() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("LocalContext", 12, 12);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; 
x_1 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
x_2 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_3 = l_Lean_Name_mkStr2(x_2, x_1);
return x_3;
}
}
static lean_object* _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instTypeNameLocalContext() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("ContextInfo", 11, 11);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
x_2 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_3 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instTypeNameContextInfo() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = lean_mk_string_unchecked("TermInfo", 8, 8);
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; lean_object* x_2; lean_object* x_3; lean_object* x_4; 
x_1 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
x_2 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_3 = l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_;
x_4 = l_Lean_Name_mkStr3(x_3, x_2, x_1);
return x_4;
}
}
static lean_object* _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
return x_1;
}
}
static lean_object* _init_l_Lean_Widget_instTypeNameTermInfo() {
_start:
{
lean_object* x_1; 
x_1 = l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_;
return x_1;
}
}
lean_object* initialize_Lean_Elab_InfoTree(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Message(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Server_Rpc_Basic(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Server_InfoUtils(uint8_t builtin, lean_object*);
lean_object* initialize_Lean_Widget_Types(uint8_t builtin, lean_object*);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_Lean_Widget_Basic(uint8_t builtin, lean_object* w) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Lean_Elab_InfoTree(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Message(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Server_Rpc_Basic(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Server_InfoUtils(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Widget_Types(builtin, lean_io_mk_world());
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__2____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__3____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_);
l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2038268869____hygCtx___hyg_3_);
l_Lean_Widget_instTypeNameInfoWithCtx = _init_l_Lean_Widget_instTypeNameInfoWithCtx();
lean_mark_persistent(l_Lean_Widget_instTypeNameInfoWithCtx);
l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_);
l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_4075166457____hygCtx___hyg_3_);
l_Lean_Widget_instTypeNameLocalContext = _init_l_Lean_Widget_instTypeNameLocalContext();
lean_mark_persistent(l_Lean_Widget_instTypeNameLocalContext);
l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_);
l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_2318528980____hygCtx___hyg_3_);
l_Lean_Widget_instTypeNameContextInfo = _init_l_Lean_Widget_instTypeNameContextInfo();
lean_mark_persistent(l_Lean_Widget_instTypeNameContextInfo);
l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__0____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_);
l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl___closed__1____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_);
l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_ = _init_l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_();
lean_mark_persistent(l_Lean_Widget_instImpl____x40_Lean_Widget_Basic_173954553____hygCtx___hyg_3_);
l_Lean_Widget_instTypeNameTermInfo = _init_l_Lean_Widget_instTypeNameTermInfo();
lean_mark_persistent(l_Lean_Widget_instTypeNameTermInfo);
return lean_io_result_mk_ok(lean_box(0));
}
#ifdef __cplusplus
}
#endif
