import Lean.ErrorExplanations.DependsOnNoncomputable
import Lean.ErrorExplanations.InductiveParamMismatch
import Lean.ErrorExplanations.InductiveParamMissing
import Lean.ErrorExplanations.InferBinderTypeFailed
import Lean.ErrorExplanations.InferDefTypeFailed
import Lean.ErrorExplanations.RedundantMatchAlt
import Lean.ErrorExplanations.CtorResultingTypeMismatch
import Lean.ErrorExplanations.InvalidDottedIdent
