#!/usr/bin/env bash
set -euo pipefail

rm -r stage0 || true
# don't copy untracked files
for f in $(git ls-files src); do
    [[ $f != src/lake && $f != src/Leanc.lean ]] || continue
    if [[ $f == *.lean ]]; then
        f=${f#src/}
        f=${f%.lean}.c
        mkdir -p $(dirname stage0/stdlib/$f)
        cp ${CP_C_PARAMS:-} $CSRCS/$f stage0/stdlib/$f
    else
        mkdir -p $(dirname stage0/$f)
        cp $f stage0/$f
    fi
done
git add stage0
