// Zig runtime stub: int_conv.zig
// Generated by tools/generate-stubs.py

const std = @import("std");
const testing = std.testing;
const alloc = @import("alloc.zig");
const mpz_object = @import("mpz_object.zig");
const mpz_zig = @import("mpz_zig");
const object = @import("object.zig");

fn panicOutOfMemory() noreturn {
    @panic("bignum: out of memory");
}

fn scalarToInt64(o: *anyopaque) i64 {
    const raw: u32 = @truncate(object.lean_unbox(o));
    const signed: i32 = @bitCast(raw);
    return signed;
}

fn intToMpz(o: *anyopaque) mpz_zig.Mpz {
    if (object.lean_is_scalar(o)) {
        return mpz_zig.Mpz.initSet(std.heap.c_allocator, scalarToInt64(o)) catch panicOutOfMemory();
    }

    var value = mpz_zig.Mpz.init(std.heap.c_allocator) catch panicOutOfMemory();
    value.copy(mpz_object.mpzValue(o)) catch panicOutOfMemory();
    return value;
}

fn truncateSigned(comptime T: type, o: *anyopaque) T {
    var value = intToMpz(o);
    defer value.deinit();

    var truncated = mpz_zig.Mpz.init(std.heap.c_allocator) catch panicOutOfMemory();
    defer truncated.deinit();
    truncated.smodPow2(&value, @bitSizeOf(T)) catch panicOutOfMemory();
    return @intCast(truncated.getInt() catch unreachable);
}

export fn lean_int8_of_big_int(a: *anyopaque) callconv(.c) i8 {
    return truncateSigned(i8, a);
}

export fn lean_int16_of_big_int(a: *anyopaque) callconv(.c) i16 {
    return truncateSigned(i16, a);
}

export fn lean_int32_of_big_int(a: *anyopaque) callconv(.c) i32 {
    return truncateSigned(i32, a);
}

export fn lean_int64_of_big_int(a: *anyopaque) callconv(.c) i64 {
    return truncateSigned(i64, a);
}

export fn lean_isize_of_big_int(a: *anyopaque) callconv(.c) isize {
    return truncateSigned(isize, a);
}

fn freeIntResult(o: *anyopaque) void {
    if (object.lean_is_scalar(o)) return;
    alloc.lean_free_object(o);
}

test "signed width conversions use two's-complement low bits" {
    const negative = mpz_object.lean_alloc_mpz();
    defer alloc.lean_free_object(negative);
    try mpz_object.mpzValue(negative).setStr(16, "-10000000000000000123456789ABCDEF0");

    try testing.expectEqual(@as(i8, 0x10), lean_int8_of_big_int(negative));
    try testing.expectEqual(@as(i16, 0x2110), lean_int16_of_big_int(negative));
    try testing.expectEqual(@as(i32, 0x65432110), lean_int32_of_big_int(negative));
    try testing.expectEqual(@as(i64, @bitCast(@as(u64, 0xedcba98765432110))), lean_int64_of_big_int(negative));
    try testing.expectEqual(@as(usize, 8), @sizeOf(usize));
    try testing.expectEqual(@as(isize, @bitCast(@as(usize, 0xedcba98765432110))), lean_isize_of_big_int(negative));
}

test "signed width conversions keep negative ones and positives" {
    const neg_one = mpz_object.lean_alloc_mpz();
    defer freeIntResult(neg_one);
    try mpz_object.mpzValue(neg_one).set(@as(i8, -1));
    try testing.expectEqual(@as(i8, -1), lean_int8_of_big_int(neg_one));
    try testing.expectEqual(@as(i16, -1), lean_int16_of_big_int(neg_one));
    try testing.expectEqual(@as(i32, -1), lean_int32_of_big_int(neg_one));
    try testing.expectEqual(@as(i64, -1), lean_int64_of_big_int(neg_one));
    try testing.expectEqual(@as(isize, -1), lean_isize_of_big_int(neg_one));

    const positive = mpz_object.lean_alloc_mpz();
    defer freeIntResult(positive);
    try mpz_object.mpzValue(positive).setStr(10, "18446744073709551617");
    try testing.expectEqual(@as(i8, 1), lean_int8_of_big_int(positive));
    try testing.expectEqual(@as(i16, 1), lean_int16_of_big_int(positive));
    try testing.expectEqual(@as(i32, 1), lean_int32_of_big_int(positive));
    try testing.expectEqual(@as(i64, 1), lean_int64_of_big_int(positive));
    try testing.expectEqual(@as(isize, 1), lean_isize_of_big_int(positive));
}
