// Zig runtime stub: slice.zig
// Generated by tools/generate-stubs.py

const std = @import("std");

export fn lean_slice_hash(_arg0: *anyopaque) callconv(.c) u64 {
    _ = _arg0;
    @panic("unimplemented: lean_slice_hash");
}

export fn lean_slice_dec_lt(_s1: *anyopaque, _s2: *anyopaque) callconv(.c) u8 {
    _ = _s1;
    _ = _s2;
    @panic("unimplemented: lean_slice_dec_lt");
}

test "slice stub compiles" {
    // Stubs are compile-only for now
}
