import Grove.Framework
import GroveStdlib.Generated.«sequential-container-order-instances»
import GroveStdlib.Generated.«associative-query-operations»
import GroveStdlib.Generated.«associative-creation-operations»
import GroveStdlib.Generated.«associative-modification-operations»
import GroveStdlib.Generated.«associative-create-then-query»
import GroveStdlib.Generated.«associative-all-operations-covered»
import GroveStdlib.Generated.«numeric-order-instances»
import GroveStdlib.Generated.«slice-producing»
import GroveStdlib.Generated.«slice-producing-complete»
import GroveStdlib.Generated.«string-order-instances»

/-
This file is autogenerated by grove. You can manually edit it, for example to resolve merge
conflicts, but be careful.
-/

open Grove.Framework Widget

namespace GroveStdlib.Generated

def restoreState : RestoreStateM Unit := do
  «sequential-container-order-instances».restoreState
  «associative-query-operations».restoreState
  «associative-creation-operations».restoreState
  «associative-modification-operations».restoreState
  «associative-create-then-query».restoreState
  «associative-all-operations-covered».restoreState
  «numeric-order-instances».restoreState
  «slice-producing».restoreState
  «slice-producing-complete».restoreState
  «string-order-instances».restoreState
  return ()
