#!/usr/bin/env bash
source ../../env_bench.sh
source "$TEST_DIR/util.sh"

PREFIX="lake/inundation"
rm -f measurements.jsonl

echo "Running $PREFIX/build clean"
cp lakefile.lean lakefile-clean.lean
lake -f lakefile-clean.lean -R -K test=Clean run mkBuild
lake -f lakefile-clean.lean build
"$TEST_DIR/measure.py" -t "$PREFIX/build clean" -d -a -- \
  bash -c "lake -f lakefile-clean.lean clean && lake -f lakefile-clean.lean build"

echo "Running $PREFIX/build no-op"
cp lakefile.lean lakefile-nop.lean
lake -f lakefile-nop.lean -R -K test=Nop run mkBuild
lake -f lakefile-nop.lean build
"$TEST_DIR/measure.py" -t "$PREFIX/build no-op" -d -a -- \
  lake -f lakefile-nop.lean build

echo "Running $PREFIX/config elab"
cp lakefile.lean lakefile-rc.lean
"$TEST_DIR/measure.py" -t "$PREFIX/config elab" -d -a -- \
  lake -f lakefile-rc.lean -R run nop

echo "Running $PREFIX/config import"
lake run nop
"$TEST_DIR/measure.py" -t "$PREFIX/config import" -d -a -- \
  lake run nop

echo "Running $PREFIX/config tree"
lake run mkTree
lake -d test/tree update
"$TEST_DIR/measure.py" -t "$PREFIX/config tree" -d -a -- \
  lake -d test/tree run nop

echo "Running $PREFIX/env"
lake env true
"$TEST_DIR/measure.py" -t "$PREFIX/env" -d -a -- \
  lake env true

echo "Running $PREFIX/startup"
"$TEST_DIR/measure.py" -t "$PREFIX/startup" -d -a -- \
  lake self-check
