name: Actionlint
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'
  merge_group:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: actionlint
      uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
      with:
        pyflakes: false # we do not use python scripts
