name: Grove Build

on:
  workflow_dispatch:
    inputs:
      base-ref:
        description: "Base reference for comparison"
        required: false
        type: string
  workflow_call:
    inputs:
      base-ref:
        description: "Base reference for comparison"
        required: false
        type: string

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch upstream invalidated facts
        if: inputs.base-ref != ''
        id: fetch-upstream
        uses: TwoFx/grove-action/fetch-upstream@master
        with:
          artifact-name: grove-invalidated-facts
          base-ref: ${{ inputs.base-ref }}

  build-and-deploy:
    needs: fetch-upstream
    runs-on: ubuntu-latest

    steps:
      - name: Download toolchain for this commit
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          commit: ${{ github.sha }}
          workflow: ci.yml
          path: artifacts
          name: build-Linux.*
          name_is_regexp: true

      - name: Unpack toolchain
        id: unpack-toolchain
        run: |
          cd artifacts
          # Find the tar.zst file
          TAR_FILE=$(find . -name "lean-*.tar.zst" -type f | head -1)
          if [ -z "$TAR_FILE" ]; then
            echo "Error: No lean-*.tar.zst file found"
            exit 1
          fi
          echo "Found archive: $TAR_FILE"

          # Extract the archive
          tar --zstd -xf "$TAR_FILE"

          # Find the extracted directory name
          LEAN_DIR=$(find . -maxdepth 1 -name "lean-*" -type d | head -1)
          if [ -z "$LEAN_DIR" ]; then
            echo "Error: No lean-* directory found after extraction"
            exit 1
          fi
          echo "Extracted directory: $LEAN_DIR"
          echo "lean-dir=$LEAN_DIR" >> "$GITHUB_OUTPUT"

      - name: Build
        id: build
        uses: TwoFx/grove-action/build@master
        with:
          project-path: doc/std/grove
          script-name: grove-stdlib
          invalidated-facts-artifact-name: grove-invalidated-facts
          comment-artifact-name: grove-comment
          toolchain-id: lean4
          toolchain-path: artifacts/${{ steps.unpack-toolchain.outputs.lean-dir }}
